name: Myworkflow file
on:
  push:
    branches: [main]

jobs:
  builds:
  #create VM with ubuntu OS
    runs-on: Ubuntu-20.04
    name: My Build
  
    steps:
    #first step to say hello
      - name: greeting steps
        run: | 
          echo "Hello there"

      - name: Checkout my codes
        uses: actions/checkout@v4
      - name: print content
        run: |
          ls

      - name: Installing Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: check version of python
        run: |
          python --version
          
      #installing dependencies if any
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt]; then pip install -r requirements.txt; fi
          
        
