name: My Second workflow
on:
  pull_request:
    branches: [main]

jobs:
  builds2:
    runs-on: Ubuntu-20.04
    name: My Build
  
    steps:
      # first step to say hello
      - name: greeting steps
        run: |
          echo "Hello there"

      - name: Checkout my codes
        uses: actions/checkout@v4

      - name: print content
        run: |
          ls

      - name: Installing Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: check version of python
        run: |
          python --version
          
      # installing dependencies if any
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest pytest-cov
          
      # begin test
      - name: testing with Pytest
        run: |
          pytest -v --cov --junitxml=report.xml

      # this is where we access the hidden repo
      - name: Checkout Hidden Repo
        uses: actions/checkout@v4
        with:
          repository: ben10jh/UOBHidden
          path: hiddenfolder
          token: ${{ secrets.SECRETUOB }}

      # this prints out the hidden files
      - name: print out hidden things
        run: |
          ls
          cd hiddenfolder
          ls
          cat hiddenText.txt

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          junit_files: '*.xml'
